{
 "title": "JMeter Dashboard",
 "description": "Monitor your Jmeter test with InfluxDB and Grafana.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "label": "Application Name",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   {
    "name": "aggregation",
    "label": "Aggregation Interval",
    "query": "1s,10s,30s,60s,600s,1800s,3600s"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Users",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"maxAT\") FROM \"jmeter\" WHERE \"transaction\" = 'internal' AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Hits/Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total Hits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hit\" FROM \"jmeter\" WHERE \"application\" =~ /^$Application$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Transactions Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ok' OR \"statut\" = 'ko') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Passed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ok') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"statut\" = 'ko') AND \"application\" =~ /^$Application$/ AND $timeFilter GROUP BY time($aggregation) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^$request$/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "Transactions/Second (Pass)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT \"count\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\" ",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions/Second (Fail)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$aggregation" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT \"count\" FROM \"jmeter\" WHERE (\"statut\" = 'ko' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\" ",
     "select": [
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "all" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  },
  {
   "title": "Transactions Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT \"avg\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$Application$/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/^$Application$/" }
     ]
    }
   ]
  }
 ]
}